### PR TITLE
1.0.0-prerelease

### LINKED ISSUE #4: Refactor into an npm package, serverless-plugin, and provide example handlers as individual Serverless functions
It seems to make a lot of sense to turn serverless-chrome into an npm package, and separate Serverless plugin.

The plugin would hook into the Serverless `after:createDeploymentArtifacts` life cycle event and wrap around the handler function. The wrapper would then make sure that headless Chrome is running before calling the wrapped handler function.

https://serverless.com/framework/docs/providers/aws/guide/plugins/

1. [x] update for nodejs v6.10 (and remove Buffer.from hack/polyfill)
1. [x] refactor chrome bundle and chrome spawning into an npm package (npm: `lambda-chrome` ?)
1. [x] Serverless plugin, using npm package
1. [x] use [Rollup](https://github.com/rollup/rollup)([docs](https://rollupjs.org/#introduction)) for npm packages
1. [x] remove `serverless-webpack` plugin dependency
1. [ ] create Serverless functions for each example handler
1. [x] ~change postinstall script to create `serverless.yml` instead of `config.js` from one of the example `serverless.yml` files~
1. [ ] update all the documentation

### LINKED ISSUE #5: Get linting and unit tests up to snuff
1. [ ] finish writing all unit tests
1. [ ] make linter happy
1. [ ] CircleCi build should pass
1. [ ] get coverage reports working

### LINKED ISSUE #36: Return binary
In your comments you mention `it's not possible to send binary via AWS API Gateway as it expects JSON response from Lambda`. You can do it with:

serverless.yml
```yml
plugins:
  - serverless-apigwy-binary # <-- Add
...
functions:
  run:
    description: Run headless Chromium
    memorySize: 1536
    timeout: 30
    handler: handler.run

    events:
      - http:
          path: chrome
          method: get
          contentHandling: CONVERT_TO_BINARY. # <-- Add
```

handler:
```js
{
                        statusCode: 200,
                        isBase64Encoded: true,  // <-- Add
                        body: screenshot.toString('base64')
}
```

I'm working on a PR right now.

### LINKED ISSUE #42: Unable to deploy serverless examples from develop branch
Hello @adieuadieu,

This is a great project, and write-up that you've put together - especially consolidating the output of the discussion about getting Headless Chrome running on Lambda! And also... getting it working!

I was playing around with the develop branch today, as I'd really like to prototype a few things; using this would be a big help if in future someone wants to add a headless-chrome protocol plugin to Nutch.

So, back to the issue - you may already be aware of it as it only pertains to the `develop` branch. When trying to install / deploy the examples on the develop branch, I always end up at the same error from `serverless deploy`; I tried to recreate my installation steps below (I've tried with `npm install --save-dev`, `npm install --save`), and am unable to get it going :(

I'm not super familiar with Serverless, so it may be the case that I'm missing something completely obvious!

```sh
momer@ubuntuk:~$ serverless install -u https://github.com/adieuadieu/serverless-chrome/tree/develop/examples/serverless-framework/aws

Serverless: Downloading and installing "aws"...
Serverless: Successfully installed "aws"

momer@ubuntuk:~$ cd aws/
momer@ubuntuk:~/aws$ npm install --save-dev serverless-plugin-chrome

> @serverless-chrome/lambda@1.0.0-5 postinstall /home/momer/aws/node_modules/serverless-plugin-chrome/node_modules/@serverless-chrome/lambda
> node scripts/postinstall.js

Downloading precombiled headless Chrome binary for AWS Lambda
@serverless-chrome/functions-serverless-framework@1.0.0 /home/momer/aws
└─┬ serverless-plugin-chrome@1.0.0-9
  ├─┬ @serverless-chrome/lambda@1.0.0-5
  │ └─┬ extract-zip@1.6.5
  │   ├─┬ concat-stream@1.6.0
  │   │ ├─┬ readable-stream@2.3.3
  │   │ │ ├── core-util-is@1.0.2
  │   │ │ ├── isarray@1.0.0
  │   │ │ ├── process-nextick-args@1.0.7
  │   │ │ ├── safe-buffer@5.1.1
  │   │ │ ├── string_decoder@1.0.3
  │   │ │ └── util-deprecate@1.0.2
  │   │ └── typedarray@0.0.6
  │   ├─┬ debug@2.2.0
  │   │ └── ms@0.7.1
  │   ├─┬ mkdirp@0.5.0
  │   │ └── minimist@0.0.8
  │   └─┬ yauzl@2.4.1
  │     └─┬ fd-slicer@1.0.1
  │       └── pend@1.2.0
  ├─┬ fs-p@2.0.0
  │ └─┬ fs-extra@2.1.2
  │   ├── graceful-fs@4.1.11
  │   └── jsonfile@2.4.0
  └─┬ globby@6.1.0
    ├─┬ array-union@1.0.2
    │ └── array-uniq@1.0.3
    ├─┬ glob@7.1.2
    │ ├── fs.realpath@1.0.0
    │ ├─┬ inflight@1.0.6
    │ │ └── wrappy@1.0.2
    │ ├── inherits@2.0.3
    │ ├─┬ minimatch@3.0.4
    │ │ └─┬ brace-expansion@1.1.8
    │ │   ├── balanced-match@1.0.0
    │ │   └── concat-map@0.0.1
    │ ├── once@1.4.0
    │ └── path-is-absolute@1.0.1
    ├── object-assign@4.1.1
    ├── pify@2.3.0
    └─┬ pinkie-promise@2.0.1
      └── pinkie@2.0.4

momer@ubuntuk:~/aws$ npm install --save-dev

> spawn-sync@1.0.15 postinstall /home/momer/aws/node_modules/spawn-sync
> node postinstall


> @serverless-chrome/lambda@1.0.0-5 postinstall /home/momer/aws/node_modules/@serverless-chrome/lambda
> node scripts/postinstall.js

Downloading precombiled headless Chrome binary for AWS Lambda

> serverless@1.17.0 postinstall /home/momer/aws/node_modules/serverless
> node ./scripts/postinstall.js

@serverless-chrome/functions-serverless-framework@1.0.0 /home/momer/aws
├── @serverless-chrome/lambda@1.0.0-5
├─┬ ava@0.20.0
│ ├─┬ @ava/babel-preset-stage-4@1.1.0
│ │ ├── babel-plugin-check-es2015-constants@6.22.0
│ │ ├── babel-plugin-syntax-trailing-function-commas@6.22.0
│ │ ├─┬ babel-plugin-transform-async-to-generator@6.24.1
│ │ │ ├── babel-helper-remap-async-to-generator@6.24.1
│ │ │ └── babel-plugin-syntax-async-functions@6.13.0
│ │ ├── babel-plugin-transform-es2015-destructuring@6.23.0
│ │ ├─┬ babel-plugin-transform-es2015-function-name@6.24.1
│ │ │ └── babel-helper-function-name@6.24.1
│ │ ├─┬ babel-plugin-transform-es2015-modules-commonjs@6.24.1
│ │ │ └── babel-plugin-transform-strict-mode@6.24.1
│ │ ├─┬ babel-plugin-transform-es2015-parameters@6.24.1
│ │ │ ├─┬ babel-helper-call-delegate@6.24.1
│ │ │ │ └── babel-helper-hoist-variables@6.24.1
│ │ │ └── babel-helper-get-function-arity@6.24.1
│ │ ├── babel-plugin-transform-es2015-spread@6.22.0
│ │ ├─┬ babel-plugin-transform-es2015-sticky-regex@6.24.1
│ │ │ └── babel-helper-regex@6.24.1
│ │ ├─┬ babel-plugin-transform-es2015-unicode-regex@6.24.1
│ │ │ └─┬ regexpu-core@2.0.0
│ │ │   ├── regenerate@1.3.2
│ │ │   ├── regjsgen@0.2.0
│ │ │   └─┬ regjsparser@0.1.5
│ │ │     └── jsesc@0.5.0
│ │ ├─┬ babel-plugin-transform-exponentiation-operator@6.24.1
│ │ │ ├─┬ babel-helper-builder-binary-assignment-operator-visitor@6.24.1
│ │ │ │ └── babel-helper-explode-assignable-expression@6.24.1
│ │ │ └── babel-plugin-syntax-exponentiation-operator@6.13.0
│ │ └─┬ package-hash@1.2.0
│ │   └── md5-hex@1.3.0
│ ├─┬ @ava/babel-preset-transform-test-files@3.0.0
│ │ ├── @ava/babel-plugin-throws-helper@2.0.0
│ │ └─┬ babel-plugin-espower@2.3.2
│ │   ├─┬ call-matcher@1.0.1
│ │   │ └── deep-equal@1.0.1
│ │   ├─┬ espower-location-detector@1.0.0
│ │   │ └── is-url@1.2.2
│ │   └── espurify@1.7.0
│ ├─┬ @ava/write-file-atomic@2.2.0
│ │ ├── imurmurhash@0.1.4
│ │ └── slide@1.1.6
│ ├── @concordance/react@1.0.0
│ ├── ansi-escapes@2.0.0
│ ├─┬ ansi-styles@3.1.0
│ │ └─┬ color-convert@1.9.0
│ │   └── color-name@1.1.2
│ ├── arr-flatten@1.1.0
│ ├── arrify@1.0.1
│ ├── auto-bind@1.1.0
│ ├─┬ ava-init@0.2.1
│ │ ├── arr-exclude@1.0.0
│ │ ├─┬ execa@0.7.0
│ │ │ ├─┬ cross-spawn@5.1.0
│ │ │ │ ├─┬ lru-cache@4.1.1
│ │ │ │ │ ├── pseudomap@1.0.2
│ │ │ │ │ └── yallist@2.1.2
│ │ │ │ ├─┬ shebang-command@1.2.0
│ │ │ │ │ └── shebang-regex@1.0.0
│ │ │ │ └─┬ which@1.2.14
│ │ │ │   └── isexe@2.0.0
│ │ │ ├─┬ npm-run-path@2.0.2
│ │ │ │ └── path-key@2.0.1
│ │ │ ├── p-finally@1.0.0
│ │ │ └── strip-eof@1.0.0
│ │ ├── has-yarn@1.0.0
│ │ ├─┬ read-pkg-up@2.0.0
│ │ │ └─┬ read-pkg@2.0.0
│ │ │   └── path-type@2.0.0
│ │ └─┬ write-pkg@3.1.0
│ │   ├─┬ sort-keys@2.0.0
│ │   │ └── is-plain-obj@1.1.0
│ │   └─┬ write-json-file@2.2.0
│ │     ├── detect-indent@5.0.0
│ │     └── sort-keys@1.1.2
│ ├─┬ babel-core@6.25.0
│ │ ├─┬ babel-code-frame@6.22.0
│ │ │ └── js-tokens@3.0.2
│ │ ├─┬ babel-generator@6.25.0
│ │ │ ├─┬ detect-indent@4.0.0
│ │ │ │ └── repeating@2.0.1
│ │ │ ├── jsesc@1.3.0
│ │ │ └── trim-right@1.0.1
│ │ ├── babel-helpers@6.24.1
│ │ ├── babel-messages@6.23.0
│ │ ├── babel-template@6.25.0
│ │ ├─┬ babel-traverse@6.25.0
│ │ │ └── invariant@2.2.2
│ │ ├─┬ babel-types@6.25.0
│ │ │ └── to-fast-properties@1.0.3
│ │ ├── babylon@6.17.4
│ │ ├── json5@0.5.1
│ │ ├── private@0.1.7
│ │ └── source-map@0.5.6
│ ├── bluebird@3.5.0
│ ├─┬ caching-transform@1.0.1
│ │ ├── md5-hex@1.3.0
│ │ ├── mkdirp@0.5.1
│ │ └── write-file-atomic@1.3.4
│ ├─┬ chalk@1.1.3
│ │ ├── ansi-styles@2.2.1
│ │ ├── escape-string-regexp@1.0.5
│ │ ├── has-ansi@2.0.0
│ │ └── supports-color@2.0.0
│ ├─┬ chokidar@1.7.0
│ │ ├─┬ anymatch@1.3.0
│ │ │ └─┬ micromatch@2.3.11
│ │ │   ├── arr-diff@2.0.0
│ │ │   ├── array-unique@0.2.1
│ │ │   ├─┬ braces@1.8.5
│ │ │   │ ├─┬ expand-range@1.8.2
│ │ │   │ │ └─┬ fill-range@2.2.3
│ │ │   │ │   ├── is-number@2.1.0
│ │ │   │ │   ├── isobject@2.1.0
│ │ │   │ │   ├─┬ randomatic@1.1.7
│ │ │   │ │   │ ├─┬ is-number@3.0.0
│ │ │   │ │   │ │ └── kind-of@3.2.2
│ │ │   │ │   │ └── kind-of@4.0.0
│ │ │   │ │   └── repeat-string@1.6.1
│ │ │   │ ├── preserve@0.2.0
│ │ │   │ └── repeat-element@1.1.2
│ │ │   ├─┬ expand-brackets@0.1.5
│ │ │   │ └── is-posix-bracket@0.1.1
│ │ │   ├── extglob@0.3.2
│ │ │   ├── filename-regex@2.0.1
│ │ │   ├─┬ kind-of@3.2.2
│ │ │   │ └── is-buffer@1.1.5
│ │ │   ├─┬ object.omit@2.0.1
│ │ │   │ ├─┬ for-own@0.1.5
│ │ │   │ │ └── for-in@1.0.2
│ │ │   │ └── is-extendable@0.1.1
│ │ │   ├─┬ parse-glob@3.0.4
│ │ │   │ ├── glob-base@0.3.0
│ │ │   │ └── is-dotfile@1.0.3
│ │ │   └─┬ regex-cache@0.4.3
│ │ │     ├── is-equal-shallow@0.1.3
│ │ │     └── is-primitive@2.0.0
│ │ ├── async-each@1.0.1
│ │ ├── glob-parent@2.0.0
│ │ ├─┬ is-binary-path@1.0.1
│ │ │ └── binary-extensions@1.8.0
│ │ ├─┬ is-glob@2.0.1
│ │ │ └── is-extglob@1.0.0
│ │ └─┬ readdirp@2.1.0
│ │   └── set-immediate-shim@1.0.1
│ ├── clean-stack@1.3.0
│ ├── clean-yaml-object@0.1.0
│ ├─┬ cli-cursor@2.1.0
│ │ └─┬ restore-cursor@2.0.0
│ │   └─┬ onetime@2.0.1
│ │     └── mimic-fn@1.1.0
│ ├── cli-spinners@1.0.0
│ ├─┬ cli-truncate@1.0.0
│ │ ├── slice-ansi@0.0.4
│ │ └─┬ string-width@2.1.0
│ │   ├── is-fullwidth-code-point@2.0.0
│ │   └─┬ strip-ansi@4.0.0
│ │     └── ansi-regex@3.0.0
│ ├─┬ co-with-promise@4.6.0
│ │ └─┬ pinkie-promise@1.0.0
│ │   └── pinkie@1.0.0
│ ├─┬ code-excerpt@2.1.0
│ │ └── convert-to-spaces@1.0.2
│ ├── common-path-prefix@1.0.0
│ ├─┬ concordance@2.0.0
│ │ ├── esutils@2.0.2
│ │ ├── fast-diff@1.1.1
│ │ ├── function-name-support@0.2.0
│ │ ├── js-string-escape@1.0.1
│ │ ├── lodash.clonedeep@4.5.0
│ │ ├── lodash.flattendeep@4.4.0
│ │ └── well-known-symbols@1.0.0
│ ├── convert-source-map@1.5.0
│ ├─┬ core-assert@0.2.1
│ │ ├── buf-compare@1.0.1
│ │ └── is-error@2.2.1
│ ├─┬ currently-unhandled@0.4.1
│ │ └── array-find-index@1.0.2
│ ├── dot-prop@4.1.1
│ ├─┬ empower-core@0.6.2
│ │ └── call-signature@0.0.2
│ ├── equal-length@1.0.1
│ ├── figures@2.0.0
│ ├─┬ find-cache-dir@0.1.1
│ │ ├── commondir@1.0.1
│ │ ├── mkdirp@0.5.1
│ │ └─┬ pkg-dir@1.0.0
│ │   └─┬ find-up@1.1.2
│ │     └── path-exists@2.1.0
│ ├── fn-name@2.0.1
│ ├── get-port@3.1.0
│ ├── has-flag@2.0.0
│ ├─┬ hullabaloo-config-manager@1.1.1
│ │ ├── es6-error@4.0.2
│ │ ├── lodash.isequal@4.5.0
│ │ ├── pkg-dir@2.0.0
│ │ └── resolve-from@3.0.0
│ ├── ignore-by-default@1.0.1
│ ├─┬ import-local@0.1.1
│ │ ├── pkg-dir@2.0.0
│ │ └── resolve-cwd@2.0.0
│ ├── indent-string@3.1.0
│ ├── is-ci@1.0.10
│ ├── is-generator-fn@1.0.0
│ ├── is-obj@1.0.1
│ ├─┬ is-observable@0.2.0
│ │ └── symbol-observable@0.2.4
│ ├── is-promise@2.1.0
│ ├─┬ js-yaml@3.9.0
│ │ ├─┬ argparse@1.0.9
│ │ │ └── sprintf-js@1.0.3
│ │ └── esprima@4.0.0
│ ├─┬ last-line-stream@1.0.0
│ │ └─┬ through2@2.0.3
│ │   └── xtend@4.0.1
│ ├── lodash.clonedeepwith@4.5.0
│ ├── lodash.debounce@4.0.8
│ ├── lodash.difference@4.5.0
│ ├── lodash.flatten@4.4.0
│ ├─┬ loud-rejection@1.6.0
│ │ └── signal-exit@3.0.2
│ ├── make-dir@1.0.0
│ ├── matcher@0.1.2
│ ├─┬ md5-hex@2.0.0
│ │ └── md5-o-matic@0.1.1
│ ├─┬ meow@3.7.0
│ │ ├─┬ camelcase-keys@2.1.0
│ │ │ └── camelcase@2.1.1
│ │ ├── decamelize@1.2.0
│ │ ├── map-obj@1.0.1
│ │ ├── minimist@1.2.0
│ │ ├─┬ normalize-package-data@2.4.0
│ │ │ ├── hosted-git-info@2.5.0
│ │ │ ├─┬ is-builtin-module@1.0.0
│ │ │ │ └── builtin-modules@1.1.1
│ │ │ └─┬ validate-npm-package-license@3.0.1
│ │ │   ├─┬ spdx-correct@1.0.2
│ │ │   │ └── spdx-license-ids@1.2.2
│ │ │   └── spdx-expression-parse@1.0.4
│ │ ├─┬ read-pkg-up@1.0.1
│ │ │ ├─┬ find-up@1.1.2
│ │ │ │ └── path-exists@2.1.0
│ │ │ └─┬ read-pkg@1.1.0
│ │ │   ├─┬ load-json-file@1.1.0
│ │ │   │ └── strip-bom@2.0.0
│ │ │   └── path-type@1.1.0
│ │ ├─┬ redent@1.0.0
│ │ │ ├── indent-string@2.1.0
│ │ │ └─┬ strip-indent@1.0.1
│ │ │   └── get-stdin@4.0.1
│ │ └── trim-newlines@1.0.0
│ ├── ms@1.0.0
│ ├─┬ multimatch@2.1.0
│ │ └── array-differ@1.0.0
│ ├─┬ observable-to-promise@0.5.0
│ │ └── symbol-observable@1.0.4
│ ├── option-chain@0.1.1
│ ├─┬ package-hash@2.0.0
│ │ └── release-zalgo@1.0.0
│ ├─┬ pkg-conf@2.0.0
│ │ ├─┬ find-up@2.1.0
│ │ │ └─┬ locate-path@2.0.0
│ │ │   ├─┬ p-locate@2.0.0
│ │ │   │ └── p-limit@1.1.0
│ │ │   └── path-exists@3.0.0
│ │ └─┬ load-json-file@2.0.0
│ │   └─┬ parse-json@2.2.0
│ │     └─┬ error-ex@1.3.1
│ │       └── is-arrayish@0.2.1
│ ├─┬ plur@2.1.2
│ │ └── irregular-plurals@1.3.0
│ ├─┬ pretty-ms@2.1.0
│ │ ├─┬ is-finite@1.0.2
│ │ │ └── number-is-nan@1.0.1
│ │ ├── parse-ms@1.0.1
│ │ └── plur@1.0.0
│ ├── require-precompiled@0.1.0
│ ├─┬ resolve-cwd@1.0.0
│ │ └── resolve-from@2.0.0
│ ├── slash@1.0.0
│ ├── source-map-support@0.4.15
│ ├── stack-utils@1.0.1
│ ├─┬ strip-ansi@3.0.1
│ │ └── ansi-regex@2.1.1
│ ├─┬ strip-bom-buf@1.0.0
│ │ └── is-utf8@0.2.1
│ ├─┬ supports-color@3.2.3
│ │ └── has-flag@1.0.0
│ ├─┬ time-require@0.1.2
│ │ ├─┬ chalk@0.4.0
│ │ │ ├── ansi-styles@1.0.0
│ │ │ ├── has-color@0.1.7
│ │ │ └── strip-ansi@0.1.1
│ │ ├── date-time@0.1.1
│ │ ├─┬ pretty-ms@0.2.2
│ │ │ └── parse-ms@0.1.2
│ │ └── text-table@0.2.0
│ ├── trim-off-newlines@1.0.1
│ ├─┬ unique-temp-dir@1.0.0
│ │ ├── mkdirp@0.5.1
│ │ ├── os-tmpdir@1.0.2
│ │ └── uid2@0.0.3
│ └─┬ update-notifier@2.2.0
│   ├─┬ boxen@1.2.0
│   │ ├── ansi-align@2.0.0
│   │ ├── camelcase@4.1.0
│   │ ├─┬ chalk@2.0.1
│   │ │ └── supports-color@4.2.0
│   │ ├── cli-boxes@1.0.0
│   │ ├── term-size@1.2.0
│   │ └─┬ widest-line@1.0.0
│   │   └─┬ string-width@1.0.2
│   │     └── is-fullwidth-code-point@1.0.0
│   ├─┬ configstore@3.1.0
│   │ └─┬ unique-string@1.0.0
│   │   └── crypto-random-string@1.0.0
│   ├── import-lazy@2.1.0
│   ├── is-npm@1.0.0
│   ├─┬ latest-version@3.1.0
│   │ └─┬ package-json@4.0.1
│   │   ├── registry-auth-token@3.3.1
│   │   └── registry-url@3.1.0
│   ├── semver-diff@2.1.0
│   └── xdg-basedir@3.0.0
├─┬ babel-register@6.24.1
│ ├─┬ babel-runtime@6.23.0
│ │ └── regenerator-runtime@0.10.5
│ ├── core-js@2.4.1
│ ├─┬ home-or-tmp@2.0.0
│ │ └── os-homedir@1.0.2
│ ├── lodash@4.17.4
│ └── mkdirp@0.5.1
├─┬ chrome-remote-interface@0.24.2
│ ├── commander@2.1.0
│ └─┬ ws@2.0.3
│   └── ultron@1.1.0
├── prettier@1.5.3
├─┬ prettier-eslint@6.4.2
│ ├── common-tags@1.4.0
│ ├── dlv@1.1.0
│ ├─┬ eslint@3.19.0
│ │ ├── doctrine@2.0.0
│ │ ├─┬ escope@3.6.0
│ │ │ ├─┬ es6-map@0.1.5
│ │ │ │ ├── d@1.0.0
│ │ │ │ ├── es5-ext@0.10.24
│ │ │ │ ├── es6-iterator@2.0.1
│ │ │ │ ├── es6-set@0.1.5
│ │ │ │ ├── es6-symbol@3.1.1
│ │ │ │ └── event-emitter@0.3.5
│ │ │ ├── es6-weak-map@2.0.2
│ │ │ └── esrecurse@4.2.0
│ │ ├─┬ espree@3.4.3
│ │ │ ├── acorn@5.1.1
│ │ │ └─┬ acorn-jsx@3.0.1
│ │ │   └── acorn@3.3.0
│ │ ├── esquery@1.0.0
│ │ ├── estraverse@4.2.0
│ │ ├─┬ file-entry-cache@2.0.0
│ │ │ └─┬ flat-cache@1.2.2
│ │ │   ├── circular-json@0.3.1
│ │ │   ├─┬ del@2.2.2
│ │ │   │ ├── globby@5.0.0
│ │ │   │ ├── is-path-cwd@1.0.0
│ │ │   │ └─┬ is-path-in-cwd@1.0.0
│ │ │   │   └── is-path-inside@1.0.0
│ │ │   └─┬ write@0.2.1
│ │ │     └── mkdirp@0.5.1
│ │ ├── globals@9.18.0
│ │ ├── ignore@3.3.3
│ │ ├─┬ inquirer@0.12.0
│ │ │ ├── ansi-escapes@1.4.0
│ │ │ ├─┬ cli-cursor@1.0.2
│ │ │ │ └─┬ restore-cursor@1.0.1
│ │ │ │   ├── exit-hook@1.1.1
│ │ │ │   └── onetime@1.1.0
│ │ │ ├── cli-width@2.1.0
│ │ │ ├── figures@1.7.0
│ │ │ ├─┬ readline2@1.0.1
│ │ │ │ ├── is-fullwidth-code-point@1.0.0
│ │ │ │ └── mute-stream@0.0.5
│ │ │ ├── run-async@0.1.0
│ │ │ ├── rx-lite@3.1.2
│ │ │ ├─┬ string-width@1.0.2
│ │ │ │ ├── code-point-at@1.1.0
│ │ │ │ └── is-fullwidth-code-point@1.0.0
│ │ │ └── through@2.3.8
│ │ ├─┬ is-my-json-valid@2.16.0
│ │ │ ├── generate-function@2.0.0
│ │ │ ├─┬ generate-object-property@1.2.0
│ │ │ │ └── is-property@1.0.2
│ │ │ └── jsonpointer@4.0.1
│ │ ├─┬ is-resolvable@1.0.0
│ │ │ └── tryit@1.0.3
│ │ ├─┬ json-stable-stringify@1.0.1
│ │ │ └── jsonify@0.0.0
│ │ ├─┬ levn@0.3.0
│ │ │ ├── prelude-ls@1.1.2
│ │ │ └── type-check@0.3.2
│ │ ├── natural-compare@1.4.0
│ │ ├─┬ optionator@0.8.2
│ │ │ ├── deep-is@0.1.3
│ │ │ ├── fast-levenshtein@2.0.6
│ │ │ └── wordwrap@1.0.0
│ │ ├── path-is-inside@1.0.2
│ │ ├── pluralize@1.2.1
│ │ ├── progress@1.1.8
│ │ ├─┬ require-uncached@1.0.3
│ │ │ ├─┬ caller-path@0.1.0
│ │ │ │ └── callsites@0.2.0
│ │ │ └── resolve-from@1.0.1
│ │ ├─┬ shelljs@0.7.8
│ │ │ ├── interpret@1.0.3
│ │ │ └─┬ rechoir@0.6.2
│ │ │   └─┬ resolve@1.3.3
│ │ │     └── path-parse@1.0.5
│ │ ├── strip-bom@3.0.0
│ │ ├── strip-json-comments@2.0.1
│ │ ├─┬ table@3.8.3
│ │ │ ├─┬ ajv@4.11.8
│ │ │ │ └── co@4.6.0
│ │ │ └── ajv-keywords@1.5.1
│ │ └── user-home@2.0.0
│ ├── lodash.merge@4.6.0
│ ├─┬ loglevel-colored-level-prefix@1.0.0
│ │ └── loglevel@1.4.1
│ ├── pretty-format@20.0.3
│ └── require-relative@0.8.7
└─┬ serverless@1.17.0
  ├─┬ apollo-client@1.8.1
  │ ├── @types/async@2.0.40
  │ ├── @types/graphql@0.9.4
  │ ├── @types/isomorphic-fetch@0.0.34
  │ ├── graphql-anywhere@3.1.0
  │ ├─┬ redux@3.7.2
  │ │ ├── lodash-es@4.17.4
  │ │ ├── loose-envify@1.3.1
  │ │ └── symbol-observable@1.0.4
  │ ├── symbol-observable@1.0.4
  │ └── whatwg-fetch@2.0.3
  ├─┬ archiver@1.3.0
  │ ├─┬ archiver-utils@1.3.0
  │ │ ├── lazystream@1.0.0
  │ │ └─┬ normalize-path@2.1.1
  │ │   └── remove-trailing-separator@1.0.2
  │ ├── async@2.5.0
  │ ├── buffer-crc32@0.2.13
  │ ├─┬ tar-stream@1.5.4
  │ │ ├── bl@1.2.1
  │ │ └── end-of-stream@1.4.0
  │ ├── walkdir@0.0.11
  │ └─┬ zip-stream@1.2.0
  │   └─┬ compress-commons@1.2.0
  │     └─┬ crc32-stream@2.0.0
  │       └── crc@3.4.4
  ├── async@1.5.2
  ├─┬ aws-sdk@2.85.0
  │ ├─┬ buffer@4.9.1
  │ │ ├── base64-js@1.2.1
  │ │ └── ieee754@1.1.8
  │ ├── crypto-browserify@1.0.9
  │ ├── events@1.1.1
  │ ├── jmespath@0.15.0
  │ ├── querystring@0.2.0
  │ ├── sax@1.2.1
  │ ├─┬ url@0.10.3
  │ │ └── punycode@1.3.2
  │ ├── uuid@3.0.1
  │ ├── xml2js@0.4.17
  │ └── xmlbuilder@4.2.1
  ├── ci-info@1.0.0
  ├─┬ download@5.0.3
  │ ├─┬ caw@2.0.0
  │ │ ├── get-proxy@1.1.0
  │ │ └── tunnel-agent@0.4.3
  │ ├─┬ decompress@4.2.0
  │ │ ├─┬ decompress-tar@4.1.0
  │ │ │ └── file-type@3.9.0
  │ │ ├─┬ decompress-tarbz2@4.1.0
  │ │ │ ├─┬ seek-bzip@1.0.5
  │ │ │ │ └─┬ commander@2.8.1
  │ │ │ │   └── graceful-readlink@1.0.1
  │ │ │ └─┬ unbzip2-stream@1.2.4
  │ │ │   └─┬ buffer@3.6.0
  │ │ │     └── base64-js@0.0.8
  │ │ ├─┬ decompress-targz@4.1.0
  │ │ │ └── file-type@4.4.0
  │ │ ├─┬ decompress-unzip@4.0.1
  │ │ │ ├── get-stream@2.3.1
  │ │ │ └── yauzl@2.8.0
  │ │ └─┬ strip-dirs@2.0.0
  │ │   └── is-natural-number@4.0.1
  │ ├─┬ filenamify@2.0.0
  │ │ ├── filename-reserved-regex@2.0.0
  │ │ ├── strip-outer@1.0.0
  │ │ └── trim-repeated@1.0.0
  │ ├── get-stream@3.0.0
  │ ├─┬ got@6.7.1
  │ │ ├─┬ create-error-class@3.0.2
  │ │ │ └── capture-stack-trace@1.0.0
  │ │ ├── duplexer3@0.1.4
  │ │ ├── is-redirect@1.0.0
  │ │ ├── is-retry-allowed@1.1.0
  │ │ ├── lowercase-keys@1.0.0
  │ │ ├── timed-out@4.0.1
  │ │ ├── unzip-response@2.0.1
  │ │ └─┬ url-parse-lax@1.0.0
  │ │   └── prepend-http@1.0.4
  │ └── mkdirp@0.5.1
  ├── filesize@3.5.10
  ├─┬ fs-extra@0.26.7
  │ ├── klaw@1.3.1
  │ └── rimraf@2.6.1
  ├── get-stdin@5.0.1
  ├─┬ graphql@0.10.4
  │ └── iterall@1.1.1
  ├── graphql-tag@2.4.2
  ├─┬ https-proxy-agent@1.0.0
  │ ├─┬ agent-base@2.1.1
  │ │ └── semver@5.0.3
  │ └── extend@3.0.1
  ├─┬ json-refs@2.1.7
  │ ├── commander@2.11.0
  │ ├── graphlib@2.1.1
  │ ├── native-promise-only@0.8.1
  │ ├─┬ path-loader@1.0.2
  │ │ └─┬ superagent@3.5.2
  │ │   ├── component-emitter@1.2.1
  │ │   ├── cookiejar@2.1.1
  │ │   ├─┬ form-data@2.2.0
  │ │   │ ├── asynckit@0.4.0
  │ │   │ ├─┬ combined-stream@1.0.5
  │ │   │ │ └── delayed-stream@1.0.0
  │ │   │ └─┬ mime-types@2.1.15
  │ │   │   └── mime-db@1.27.0
  │ │   ├── formidable@1.1.1
  │ │   ├── methods@1.1.2
  │ │   ├── mime@1.3.6
  │ │   └── qs@6.5.0
  │ └─┬ uri-js@3.0.2
  │   └── punycode@2.1.0
  ├── jwt-decode@2.2.0
  ├── minimist@1.2.0
  ├── moment@2.18.1
  ├─┬ node-fetch@1.7.1
  │ ├─┬ encoding@0.1.12
  │ │ └── iconv-lite@0.4.18
  │ └── is-stream@1.1.0
  ├─┬ opn@5.1.0
  │ └── is-wsl@1.1.0
  ├─┬ raven@1.2.1
  │ ├── cookie@0.3.1
  │ ├── json-stringify-safe@5.0.1
  │ ├── lsmod@1.0.0
  │ ├── stack-trace@0.0.9
  │ └── uuid@3.0.0
  ├─┬ rc@1.2.1
  │ ├── deep-extend@0.4.2
  │ ├── ini@1.3.4
  │ └── minimist@1.2.0
  ├── replaceall@0.1.6
  ├── semver@5.3.0
  ├── semver-regex@1.0.0
  ├── shelljs@0.6.1
  ├─┬ tabtab@2.2.2
  │ ├─┬ inquirer@1.2.3
  │ │ ├── ansi-escapes@1.4.0
  │ │ ├─┬ cli-cursor@1.0.2
  │ │ │ └─┬ restore-cursor@1.0.1
  │ │ │   └── onetime@1.1.0
  │ │ ├─┬ external-editor@1.1.1
  │ │ │ ├─┬ spawn-sync@1.0.15
  │ │ │ │ └── os-shim@0.1.3
  │ │ │ └── tmp@0.0.29
  │ │ ├── figures@1.7.0
  │ │ ├── mute-stream@0.0.6
  │ │ ├── run-async@2.3.0
  │ │ ├── rx@4.1.0
  │ │ └─┬ string-width@1.0.2
  │ │   └── is-fullwidth-code-point@1.0.0
  │ ├── lodash.uniq@4.5.0
  │ ├── minimist@1.2.0
  │ ├─┬ mkdirp@0.5.1
  │ │ └── minimist@0.0.8
  │ └─┬ npmlog@2.0.4
  │   ├── ansi@0.3.1
  │   ├─┬ are-we-there-yet@1.1.4
  │   │ └── delegates@1.0.0
  │   └─┬ gauge@1.2.7
  │     ├── has-unicode@2.0.1
  │     ├── lodash.pad@4.5.1
  │     ├── lodash.padend@4.6.1
  │     └── lodash.padstart@4.6.1
  ├── uuid@2.0.3
  └── write-file-atomic@2.1.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

momer@ubuntuk:~/aws$ npm install --save

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

momer@ubuntuk:~/aws$ npm install --save serverless-plugin-chrome

- @serverless-chrome/lambda@1.0.0-5 node_modules/serverless-plugin-chrome/node_modules/@serverless-chrome/lambda
@serverless-chrome/functions-serverless-framework@1.0.0 /home/momer/aws
└── serverless-plugin-chrome@1.0.0-9

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

momer@ubuntuk:~/aws$ serverless deploy -v -f request-logger

Serverless: Injecting Headless Chrome...

  Error --------------------------------------------------

  ENOENT: no such file or directory, unlink '/home/momer/aws/.build/src/versionInfo.js'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.11.1
     Serverless Version:     1.17.0
```

### LINKED ISSUE #45: ENOENT: no such file or directory, lstat '/Users/me/project-name/.build/.serverless'
When running `serverless package` (and `serverless deploy`) I get an error when using `serverless-plugin-chrome`:

```
ENOENT: no such file or directory, lstat '/Users/me/project-name/.build/.serverless'
```

If I comment out the plugin from my `serverless.yml` `serverless package` works without issue (but no headless chrome).

I tried downgrading to older versions of serverless, but got the same error.

```
# serverless -v
1.17.0
```

### LINKED ISSUE #47: Plugin: Wrap only necessary functions
Implement this behavior: if `custom.chromeSomething` is undefined... Then all functions get the wrapper. If it's an array with function names, then limit it to just those functions listed by name in the array.

enable the chrome injection on a per function basis

```yaml
custom:
  chrome:
    - myFancyChromeFunction
    - anotherReallyCoolChromeFunction
```

### LINKED ISSUE #52: Unable to start chrome error
What could be causes of this? For the same url, it seems to fail randomly saying unable to start chrome. In some cases there is no error. 

2017-08-03T19:07:25.905Z	f995197a-787e-11e7-9309-41d30aecb3f9	Unhandled rejection Error: Unable to start Chrome. If you have the DEBUG env variable set,there will be more in the logs.
    at /var/task/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:304:13
    at throw (native)
    at step (/var/task/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:257:191)
    at /var/task/node_modules/@serverless-chrome/lambda/dist/bundle.cjs.js:257:402
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

### LINKED ISSUE #53: NSS_VersionCheck("3.26") failed
Hello,

I get the below at runtime when I follow the build steps and then try to run on Lambda. Has anyone come across this? Chrome was compiled on the same AMI as Lambda uses and followed the instruction in this repo.

```
[0807/144244.712736:FATAL:nss_util.cc(627)] NSS_VersionCheck("3.26") failed. NSS >= 3.26 is required
Please upgrade to the latest NSS, and if you still get this error,
contact your distribution maintainer.
```

### LINKED ISSUE #55: Should we modify post-install?
In @serverless-chrome/lambda, we are downloading chrome binaries every npm (and yarn) add/remove commands.
Should we add some check for not downloading same files all over again?

### LINKED ISSUE #57: Chrome 61
https://github.com/adieuadieu/serverless-chrome/tree/develop says the current version of Crome is 61, but the one I'm getting is 60. Any idea how to upgrade versions?

Thanks

### LINKED ISSUE #64: Google Fonts is not loaded
Hi, I have tested the chromeless with a page, and the fonts is not loading... 

The screenshot is fine, but the fonts loaded for example with [webfont loader](https://github.com/typekit/webfontloader), is not working...  

This is the example: 

```
const chromeless = new Chromeless({ remote: true, viewport: {width: 800, height: 1600} })

const screenshot = await chromeless
  .goto('https://www.genial.ly/View/Index/5901d777ba1ab76840eafbcc')
  .wait(5000)
  .screenshot()

console.log(screenshot)

await chromeless.end()

```
And [this is the link](https://www.genial.ly/View/Index/5901d777ba1ab76840eafbcc), and you can check that the font is loaded in Chrome.

Any ideas? Thanks.

### LINKED ISSUE #69: Missing package-lock.json
Package-lock.json should be commited by Authors of this solution.
I got error with babel-loader https://github.com/babel/babel-loader/issues/503 because of "^" in
```
devDependency: {
    "babel-loader": "^7.0.0",
}
```
Quick fix: before npm install, edit babel-loader dependency and point it to "~6.4.0"
Best regards!

### LINKED ISSUE #72: Please register latest pre-release build?
Looks like there hasn't been an npm update for a while, despite new commits:

```
~/$ npm view @serverless-chrome/lambda

{ name: '@serverless-chrome/lambda',
  description: 'Run headless Chrome/Chromium on AWS Lambda',
  'dist-tags': { latest: '1.0.0-5' },
  versions:
   [ '0.0.0-pre-release-1',
     '0.0.0-pre-release-2',
     '0.0.0-pre-release-3',
     '0.0.0-pre-release-4',
     '0.0.0-pre-release-5',
     '0.0.0-pre-release-5.0',
     '0.0.0-pre-release-5.1',
     '0.0.0-pre-release-5.2',
     '1.0.0-1',
     '1.0.0-2',
     '1.0.0-3',
     '1.0.0-4',
     '1.0.0-5' ],
  maintainers: [ 'adieuadieu <marco@luethy.net>' ],
  time:
   { modified: '2017-07-02T13:41:41.832Z',
     created: '2017-05-24T14:27:53.062Z',
     '0.0.0-pre-release-1': '2017-05-24T14:27:53.062Z',
     '0.0.0-pre-release-2': '2017-05-24T15:22:50.235Z',
     '0.0.0-pre-release-3': '2017-05-24T15:36:28.381Z',
     '0.0.0-pre-release-4': '2017-05-24T16:01:45.811Z',
     '0.0.0-pre-release-5': '2017-06-15T19:39:13.879Z',
     '0.0.0-pre-release-5.0': '2017-06-17T19:21:46.381Z',
     '0.0.0-pre-release-5.1': '2017-06-17T19:29:34.478Z',
     '0.0.0-pre-release-5.2': '2017-06-17T20:44:03.209Z',
     '1.0.0-1': '2017-06-18T16:38:27.294Z',
     '1.0.0-2': '2017-06-18T19:20:14.233Z',
     '1.0.0-3': '2017-06-18T19:47:39.202Z',
     '1.0.0-4': '2017-06-19T09:20:13.127Z',
     '1.0.0-5': '2017-07-02T13:41:41.832Z' },
```

Any chance to get the latest commits bundled and registered at npm?

### LINKED ISSUE #80: Reduce binary size with upx
Hey, did you try compressing the binary with https://github.com/upx/upx ? It may shrink size twice or more

### PR DESCRIPTION
**Pull request by adieuadieu**
# Todo

- [x] update documentation
- [x] fix examples
  - [x] pdf handler
- [x] use binary return in APIG in examples
- [x] publish new versions of lambda and serverless-plugin packages
- [x] test coverage for packages
- [x] test coverage for examples
- [x] linting
- [x] CircleCi
- [x] autobuild & release binaries
- [x] auto-kill chromium after 3-5? invocations and relaunch behind the scenes (use context.waitsForEmptyLoop as to not block callback?) as a workaround to #41 
- [x] #41 via the comment-out hack?
- [x] review/clean up all `# @TODO`s
- [x] `user-data.sh:72`, don't `git checkout develop`. use master
- [x] also sync example dependencies on package version

Closes #4 
Closes #5 
Closes #36 
Closes #42 
Closes #45 
Closes #47 
Closes #52 
Closes #53 
Closes #55 
Closes #57 
Closes #64 
Closes #69 
Closes #72 
Closes #80

### CODE REVIEW

File: packages/lambda/src/launcher.js [hunk 1]
```diff
@@ -0,0 +1,211 @@
...
+
+      const chrome = spawn(this.chromePath, this.flags, {
+        detached: true,
+        stdio: ['ignore', this.outFile, this.errFile],
+      })
+
+      this.chrome = chrome
+
+      // unref the chrome instance, otherwise the lambda process won't end correctly
+      if (chrome.chrome) {
```
Comment (mooyoul) [inline packages/lambda/src/launcher.js]: I just found this block during typescript migration, isn't `chrome.chrome ` always `undefined`?

Comment (adieuadieu) [reply packages/lambda/src/launcher.js]: Hm.. That's a good point. It may be a typo and was meant to be `this.chrome`?Given that as currently written it's always `undefined`, maybe the block of code is completely useless and could just be deleted....

Comment (mooyoul) [reply packages/lambda/src/launcher.js]: thanks for checking, and yeah, 👍 for `detached: true` option. 
but according to child process document, we should discuss about this:

event loop will wait for detached process by default even `detached: true` option supplied.
so lambda runtime will not ended. to accomplish ending lambda function without waiting for chrome process exists, we should call `chrome.unref()` even `detached: true` option supplied, to not include the child in its reference count from event loop

From Node.js Child Process Doc:

> By default, the parent will wait for the detached child to exit. To prevent the parent from waiting for a given subprocess, use the subprocess.unref() method. Doing so will cause the parent's event loop to not include the child in its reference count, allowing the parent to exit independently of the child, unless there is an established IPC channel between the child and parent.

Comment (mooyoul) [reply packages/lambda/src/launcher.js]: and it looks that `src/index.js` has same block too. maybe duplicated?

File: packages/lambda/src/index.js [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+  debug(`It took ${launchTime}ms to spawn chrome.`)
+
+  // unref the chrome instance, otherwise the lambda process won't end correctly
+  /* @TODO: make this an option?
+    There's an option to change callbackWaitsForEmptyEventLoop in the Lambda context
+    http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html
+    Which means you could log chrome output to cloudwatch directly
+    without unreffing chrome.
+  */
+  if (chromeInstance.chrome) {
```
Comment (mooyoul) [inline packages/lambda/src/index.js]: yeah right this part already exists on our launcher code

File: packages/lambda/src/index.js [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+        chromeFlags,
+        port,
+      })
+    } else {
+      // This let's us use chrome-launcher in local development,
+      // but omit it from the lambda function's zip artefact
+      try {
+        // eslint-disable-next-line
+        const { Launcher: LocalChromeLauncher } = require('chrome-launcher')
+        chromeInstance = new LocalChromeLauncher({ chromePath, chromeFlags: flags, port })
```
Comment (mooyoul) [inline packages/lambda/src/index.js]: i am doing typescript migration work now, everything okay except this: it makes type mismatch. 
as you know, that LocalChromeLauncher is quiet different with our LambdaLauncher, typescript complains about that because LocalChromeLauncher cannot be casted to our LambdaLauncher type safely.

Here is some example that makes me hard

```typescript
let chromeInstance: LambdaChromeLauncher | undefined;
export default async function launch() {
  // some codes
  if (shouldRunLambdaLauncher) {
    chromeInstance = new LambdaChromeLauncher(...); // okay
  } else {
     const { Launcher: LocalChromeLauncher } = require('chrome-launcher');
     chromeInstance = new LocalChromeLauncher(...); // type mismatch error!
  }
}
```

Comment (mooyoul) [reply packages/lambda/src/index.js]: btw specifying chrome-launcher package to devDependencies is one of available solution:

```
import { Launcher: LocalChromeLauncher } from 'chrome-launcher';

let chromeInstance: LambdaChromeLauncher | LocalChromeLauncher | undefined;
export default async function launch() {
  // some codes
  if (shouldRunLambdaLauncher) {
    chromeInstance = new LambdaChromeLauncher(...); // okay
  } else {
     chromeInstance = new LocalChromeLauncher(...); // okay now!
  }
}
```

how about think about this solution?

Comment (adieuadieu) [reply packages/lambda/src/index.js]: Hi @mooyoul—Hm.. I see.  My concern with importing `chrome-launcher` is that it now has to be added as a `dependency` rather than a `devDependency`? One option is to completely remove the custom `LambdaChromeLauncher` and use `chrome-launcher` for both local-development and Lambda.

Some context: Originally I wanted to use `chrome-launcher` for launching Chrome whether it was locally or on Lambda. However, at the time, the dependency tree of `chrome-launcher` was quite huge, bundling all sorts of Lighthouse stuff which itself had very large dependencies which caused a lot of bloat in the lambda-function-handler's deployment package. Because of this, I created `src/launcher.js` mostly based on the `chrome-launcher` code. However, as was pointed out by @pedro93 in #48, it seems that `chrome-launchers`'s dependency tree is no longer very large (MB-size wise)—so we could revisit using it.

A caveat with switching to using `chrome-launcher` is that, the `LaunchedChrome` interface [does not expose](https://github.com/GoogleChrome/chrome-launcher/blob/master/chrome-launcher.ts#L42) the the reference to the `spawn`ed child process, and there is no option to `unref()`, so you'd have to go behind `chrome-launcher`'s back to `unref()` the spawed `child_process`—code which would likely cause a type error in Typescript..

But.. it's still a trade-off. Right now the `serverless-chrome/lambda` package has very few dependencies—which I quite like, and is important because of the size limitations imposed on us by Lambda. Adding `chrome-launcher` adds quite a number of child dependencies including `rimraf`, which itself has a lot of nested dependencies.. 

What about something as described in the Typescript [Modules' Optional Module Loading and Other Advanced Loading Scenarios documentation](https://www.typescriptlang.org/docs/handbook/modules.html#optional-module-loading-and-other-advanced-loading-scenarios)? (I haven't tried this myself, so no guarantee that it works..)

File: packages/lambda/src/launcher.js (hunk 1 above)
Comment (adieuadieu) [reply packages/lambda/src/launcher.js]: Ah. That's probably why it still worked! In that case it could probably safely be removed from `launcher.js`.

File: packages/lambda/src/index.js (hunk 3 above)
Comment (adieuadieu) [reply packages/lambda/src/index.js]: Also, if it's an impossible blocker.. always possible to cheat:

```js
let chromeInstance: any;
```

Yes—not good. But..

Comment (mooyoul) [reply packages/lambda/src/index.js]: I needed type definition for chrome-launcher package, because currently chrome-launcher has bundled type definition, not separated package like DefinitelyTyped (e.g. @types/chrome-launcher) so that's the reason why i considered adding chrome-launcher as devDependency.

Comment (mooyoul) [reply packages/lambda/src/index.js]: yeah `any` is possible option, even it's not good-looking.
